const DESTINATIONS = {
  Japan: [
    "Fukuoka (FUK)",
    "Okinawa (OKA)",
    "Osaka (KIX)",
    "Sapporo (CTS)",
    "Tokyo (NRT)",
  ],
  China: [
    "Beijing Daxing Int'l (PKX)",
    "Beijing Capital Int'l (PEK)",
    "Beijing (PEK/PKX)",
    "Chengdu Tianfu (TFU)",
    "Chongqing (CKG)",
    "Dongguan Humen HK Macau Ferry Terminal (ZTI)",
    "Guangzhou Pazhou Ferry Terminal (PFT)",
    "Haikou (HAK)",
    "Hangzhou (HGH)",
    "HZMB ZhuHai Port (HZI)",
    "Nanjing (NKG)",
    "Sanya (SYX)",
    "Shanghai Pudong (PVG)",
    "Shanghai Hongqiao (SHA)",
    "Shanghai (SHA/PVG)",
    "Shenzhen Airport Ferry Terminal (FYG)",
    "Shenzhen Shekou Cruise Homeport (ZYK)",
    "Xi'an (XIY)",
    "Xining (XNN)",
    "Zhongshan Ferry Terminal (ZGN)",
    "Guangzhou Nansha Ferry Port (NSZ)",
    "Hulunbuir (HLD)",
    "Lijiang (LJG)",
    "Changchun (CGQ)",
  ],
  "Hong Kong": ["Hong Kong (HKG)"],
  Taiwan: ["Taipei (TPE)", "Kaohsiung (KHH)"],
  Laos: ["Vientiane (VTE)", "Luang Prabang (LPQ)"],
  Vietnam: ["Da Nang (DAD)", "Hanoi (HAN)"],
  Australia: [
    "Sydney (SYD)",
    "Melbourne (MEL)",
    "Canberra (CBR)",
    "Brisbane (BNE)",
    "Gold Coast (OOL)",
    "Sunshine Coast (MCY)",
    "Adelaide (ADL)",
    "Hobart (HBA)",
    "Launceston (LST)",
    "Cairns (CNS)",
    "Hamilton Island (HTI)",
    "Darwin (DRW)",
    "Ayers Rock (AYQ)",
    "Newcastle (NTL)",
    "Perth (PER)",
  ],
  "Northern Mariana Islands": ["Saipan (SPN)"],
  Canada: [
    "Vancouver (YVR)",
    "Montreal (YUL)",
    "Regina (YQR)",
    "Saskatoon (YXE)",
    "Edmonton (YEG)",
    "Ottawa (YOW)",
    "Winnipeg (YWG)",
    "Victoria (YYJ)",
    "Kelowna (YLW)",
    "Toronto (YYZ)",
    "Calgary (YYC)",
  ],
  Cambodia: ["Siem Reap (SAI)", "Phnom Penh (KTI)"],
  USA: ["Los Angeles (LAX)"],
  Thailand: [
    "Bangkok (BKK)",
    "Chiang Mai (CNX)",
    "Koh Samui (USM)",
    "Krabi (KBV)",
    "Phuket (HKT)",
  ],
  Indonesia: ["Bali (DPS)", "Jakarta (CGK)"],
  Maldives: ["Male (MLE)"],
  Korea: ["Seoul (ICN)"],
  Turkiye: ["Istanbul (IST)"],
};

export default DESTINATIONS;
